# Generated by Django 5.1.4 on 2024-12-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('login', models.CharField(max_length=30, verbose_name='Логин')),
                ('password', models.TextField(max_length=20, verbose_name='Пароль')),
            ],
        ),
    ]
